name: Go

on:
  push:
    branches: [ master ]
    paths:
      - 'auth-mock/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'auth-mock/**'

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth-mock
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
