# This is a basic workflow to help you get started with Actions

name: integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate secrets
        working-directory: integration
        run: ./cert-generation.sh

      - name: cypress end2end test
        working-directory: integration
        run: docker-compose up --exit-code-from=test
